config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  devise_for :users

  get "/users/search" => 'users#search'

  # complete action
  patch '/courses/:course_id/tdl/:id' => 'tdls#complete', as: :complete

  resources :users, only: [] do
  	resources :courses
  end

  resources :courses, only: [] do
  	resources :tdls
  end

  resources :courses, only: [] do
    resources :importants
  end

  resources :courses, only: [] do
    resources :goals
  end

  resources :courses, only: [] do
    resources :uploads
  end
end

app/models/tdl.rb
class Tdl < ActiveRecord::Base
	belongs_to :course
	belongs_to :user

	def self.complete
	    course = Course.find(params[:course_id])
	    tdl = course.tdls.find(params[:id])
	    tdl.complete = true
  	end

end

app/controllers/tdls_controller.rb
class TdlsController < ApplicationController
  def index    
    @course = Course.find(params[:course_id])
    @tdls = @course.tdls.all
  end

  def show
    @course = Course.find(params[:course_id])
    @tdl = @course.tdls.find(params[:id])
    @tdls = @course.tdls.all ##
  end

  def new
    @course = Course.find(params[:course_id])
    @tdl = @course.tdls.new
  end

  def edit
    @course = Course.find(params[:course_id])
    @tdl = @course.tdls.find(params[:id])
    @edit = true 
  end

  def create
    @course = Course.find(params[:course_id])
    @tdl = @course.tdls.create(tdl_params)
    @tdls = @course.tdls.all
    # render 'index'
    redirect_to user_course_path(current_user, @course) ####
  end

  def update
    @course = Course.find(params[:course_id])
    @tdl = @course.tdls.find(params[:id])
    
    @tdls = @course.tdls.all

    if @tdl.update(tdl_params)
      # render 'index'
      redirect_to user_course_path(current_user, @course) 
    else
      render 'edit'
    end
  end

  def complete
    course = Course.find(params[:course_id])
    if current_user == course.user
      @tdl = Tdl.find(params[:id])
      if @tdl.complete
        @tdl.complete = false
        @tdl.save
        redirect_to user_course_path(current_user, course)
      else
        @tdl.complete = true
        @tdl.save
        redirect_to user_course_path(current_user, course)
      end     
    else
      redirect_to root_path, alert: "Sorry, you do not have access!"
    end
  end

  def destroy
    @course = Course.find(params[:course_id])
    @tdl = @course.tdls.find(params[:id])
    @tdl.destroy
    # redirect_to course_tdls_path(@course)
    redirect_to user_course_path(current_user, @course)
  end

  private
      def tdl_params
        params.require(:tdl).permit(:date, :task, :complete ).merge(user_id: current_user.id)
      end
end

app/helpers/tdls_helper.rb
module TdlsHelper
end

app/views/tdls/_form.html.erb
<div class="row">

        <div class="col-md-4 col-md-offset-4 pad-top">
            <hr>
            <h2 class="intro-text text-center">
                <strong>New task</strong>
            </h2>
            <hr>
            <div class = "sign-up  text-center" >			    
				<%= simple_form_for([@course, @tdl]) do |f| %>

				  <div class="form-inputs" >
				    <%= f.input :date %>
				    <%= f.input :task, required: true, autofocus: true %>
				  </div>

				<% if @edit %>
					  <div class="form-actions">
					    <%= f.button :submit, "Update" %>
					  </div>
					 <% else %>
					   <div class="form-actions">
					    <%= f.button :submit, "Create" %>
					  </div>
				<% end %>

				<% end %>    
            </div>
    </div>
</div>

app/views/tdls/_index.html.erb
<table class = "table">
	<tr>
		<th>Date</th>
		<th>Task</th>
		<th>Status</th>
		<th colspan='2'></th>
	</tr>
<tbody>	
	<% @tdls.each do |tdl| %>
	<tr>
		<td><%= tdl.date %></td>
		<td><%= tdl.task %></td> 
		<% if tdl.complete %>
			<td><%= link_to complete_path(@course, tdl), method: :patch, data: { confirm: 'Oops! Not yet completed.' } do %>
				<i class="glyphicon glyphicon-ok"></i>
			<% end %>
			Complete
			</td>
		<% else %>
			<td><%= link_to complete_path(@course, tdl), method: :patch, data: { confirm: 'Welldone!' } do %>
				<i class="glyphicon glyphicon-remove"></i>
			<% end %>
			Pending
			</td>
		<% end %>
		</td>
		<% if tdl.user == current_user %>
		<td><%= link_to 'Edit', edit_course_tdl_path(@course, tdl) %></td>
		 <td><%= link_to 'Delete', course_tdl_path(@course, tdl),
          method: :delete,
          data: { confirm: 'Are you sure?' } %></td>
          <% end %>		
	</tr>
	<% end %>	
</tbody>
</table>

</br>




<% if @course.user == current_user  %>
	<%= link_to 'Add', new_course_tdl_path(@course) %>
<i class="glyphicon glyphicon-plus"></i>
<% end %>

app/views/tdls/index.html.erb
<h1>Tdls#index</h1>

<table class = "table">
	<tr>
		<th>Date</th>
		<th>Task</th>
		<th>Completed</th>
		<th colspan='2'></th>
	</tr>
<tbody>	
	<% @tdls.each do |tdl| %>
	<tr>
		<td><%= tdl.date %></td>
		<td><%= tdl.task %></td> 
		<td><%= tdl.complete %></td>
		<td><%= link_to 'Edit', edit_course_tdl_path(@course, tdl) %></td>
		 <td><%= link_to 'Delete', course_tdl_path(@course, tdl),
          method: :delete,
          data: { confirm: 'Are you sure?' } %></td>		
	</tr>
	<% end %>	
</tbody>
</table>

</br>

<%= link_to 'Add To-do-list', new_course_tdl_path(@course) %> | 
<%= link_to 'Back', user_courses_path(current_user) %>

app/views/tdls/new.html.erb
<%= render 'tdls/form' %>

app/views/tdls/show.html.erb
<h1>Tdls#show</h1>
<p>Find me in app/views/tdls/show.html.erb</p>


<table class = "table">
	<tr>
		<th>Date</th>
		<th>Task</th>
		<th>Completed</th>
		<th colspan=''></th>
	</tr>
<tbody>	
	<tr>
		<td><%= @tdl.date %></td>
		<td><%= @tdl.task %></td> 
		<td><%= @tdl.complete %></td>  		
	</tr>	
</tbody>
</table>

</br>

	<% @courses.each do |course| %>
		<% if course.user != current_user %>
			<%= link_to 'Add To-do-list', new_course_tdl_path(@course) %> | 
<%= link_to 'Back', course_tdls_path(@course) %>