config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  devise_for :users

  get "/users/search" => 'users#search'

  # complete action
  patch '/courses/:course_id/tdl/:id' => 'tdls#complete', as: :complete

  resources :users, only: [] do
  	resources :courses
  end

  resources :courses, only: [] do
  	resources :tdls
  end

  resources :courses, only: [] do
    resources :importants
  end

  resources :courses, only: [] do
    resources :goals
  end

  resources :courses, only: [] do
    resources :uploads
  end
end

app/models/important.rb
class Important < ActiveRecord::Base
	belongs_to :course
	belongs_to :user

	def self.upcoming
		where('date > ?', Time.now)
	end
end

app/controllers/importants_controller.rb
class ImportantsController < ApplicationController
  def index    
    @course = Course.find(params[:course_id])
    @importants = @course.importants.all
  end

  def show
    @course = Course.find(params[:course_id])
    @important = @course.importants.find(params[:id])
    @importants = @course.importants.all ##
  end

  def new
    @course = Course.find(params[:course_id])
    @important = @course.importants.new
  end

  def edit
    @course = Course.find(params[:course_id])
    @important = @course.importants.find(params[:id])
    @edit = true 
  end

  def create
    @course = Course.find(params[:course_id])
    @important = @course.importants.create(important_params)
    @importants = @course.importants.all
    # render 'index'
    redirect_to user_course_path(current_user, @course) ####
  end

  def update
    @course = Course.find(params[:course_id])
    @important = @course.importants.find(params[:id])
    
    @importants = @course.importants.all

    if @important.update(important_params)
      # render 'index'
      redirect_to user_course_path(current_user, @course) 
    else
      render 'edit'
    end
  end

  def destroy
    @course = Course.find(params[:course_id])
    @important = @course.importants.find(params[:id])
    @important.destroy
    # redirect_to course_tdls_path(@course)
    redirect_to user_course_path(current_user, @course)
  end

  private
      def important_params
        params.require(:important).permit(:date, :event, :remarks ).merge(user_id: current_user.id)
      end
end

app/helpers/importants_helper.rb
module ImportantsHelper
end

app/views/importants/_form.html.erb
<div class="row">

        <div class="col-md-4 col-md-offset-4 pad-top">
            <hr>
            <% if @edit %>
            <h2 class="intro-text text-center">
                <strong>Change event</strong>
            </h2>
            <% else %>
            <h2 class="intro-text text-center">
                <strong>New event</strong>
            </h2>
            <% end %> 
            <hr>
            <div class = "sign-up  text-center" >
		    	<%= simple_form_for([@course, @important]) do |f| %>

			  <div class="form-inputs" >
			    <%= f.input :date, :as => :date %>
   
			    <%= f.input :event, required: true, autofocus: true %>
			    <%= f.input :remarks, :label => 'Details' %>
			  </div>

			<% if @edit %>
				  <div class="form-actions">
				    <%= f.button :submit, "Update" %>
				  </div>
				 <% else %>
				   <div class="form-actions">
				    <%= f.button :submit, "Create" %>
				  </div>
			<% end %>

			<% end %>
    
            </div>
    </div>
</div>

app/views/importants/_index.html.erb
<table class = "table">
	<tr>
		<th>Date</th>
		<th>Event</th>
		<th>Details</th>
		<th colspan='2'></th>
	</tr>
<tbody>	
	<% @importants.each do |important| %>
	<tr>
		<td><%= important.date %></td>
		<td><%= important.event %></td> 
		<td><%= important.remarks %></td>
		<% if important.user == current_user %>
		<td><%= link_to 'Edit', edit_course_important_path(@course, important) %></td>
		 <td><%= link_to 'Delete', course_important_path(@course, important),
          method: :delete,
          data: { confirm: 'Are you sure?' } %></td>	
          <% end %>	
	</tr>
	<% end %>	
</tbody>
</table>

</br>

<% if @course.user == current_user  %>
<%= link_to 'Add', new_course_important_path(@course) %>
<i class="glyphicon glyphicon-plus"></i>
<% end %>

app/views/importants/edit.html.erb
<%= render 'form' %>

app/views/importants/new.html.erb
<%= render 'importants/form' %>

app/views/importants/show.html.erb
<h1>Importants#show</h1>
<p>Find me in app/views/importants/show.html.erb</p>

<table class = "table">
	<tr>
		<th>Date</th>
		<th>Event/th>
		<th>Remarks</th>
		<th colspan=''></th>
	</tr>
<tbody>	
	<tr>
		<td><%= @important.date %></td>
		<td><%= @important.event %></td> 
		<td><%= @important.remarks %></td>  		
	</tr>	
</tbody>
</table>

</br>

<%= link_to 'Add an event', new_course_important_path(@course) %> | 
<%= link_to 'Back', course_importants_path(@course) %>