config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  devise_for :users

  get "/users/search" => 'users#search'

  # complete action
  patch '/courses/:course_id/tdl/:id' => 'tdls#complete', as: :complete

  resources :users, only: [] do
  	resources :courses
  end

  resources :courses, only: [] do
  	resources :tdls
  end

  resources :courses, only: [] do
    resources :importants
  end

  resources :courses, only: [] do
    resources :goals
  end

  resources :courses, only: [] do
    resources :uploads
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    user_id = params[:user_id].to_i
    user = User.find(user_id)
    @courses = user.courses
  end

  def show
    @course = Course.find(params[:id])
    user_id = params[:user_id].to_i
    user = User.find(user_id)
    @courses = user.courses
    @tdls = @course.tdls.all ##
    @importants = @course.importants.all ##
    @goals = @course.goals.all ##
    @uploads = @course.uploads.all ##

    @importants = @importants.order(:date).upcoming
    @next = @importants.first
    @importants = @course.importants.all
  end

  def new
    @course = current_user.courses.new
  end

  def edit
    @course = current_user.courses.find(params[:id])
  end

  def create
    @course = current_user.courses.build(course_params)
    if @course.save
      redirect_to user_course_path(current_user, @course)
    else
      render 'new'
    end
  end

  def update
    @course = current_user.courses.find(params[:id])
    if @course.update(course_params)
      redirect_to user_course_path(current_user, @course)
    else
      render 'edit'
    end
  end

  def destroy
    @course = current_user.courses.find(params[:id])
    @course.destroy
    redirect_to user_courses_path(current_user)
  end

  private
  def course_params
    params.require(:course).permit(:name, :end_date, :public)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<div class="row">

        <div class="col-md-4 col-md-offset-4 pad-top">
            <hr>
            <h2 class="intro-text text-center">
                <strong>New course</strong>
            </h2>
            <hr>
            <div class = "sign-up  text-center" >
					<%= simple_form_for([current_user, @course]) do |f| %>

					  <div class="form-inputs">
					    <%= f.input :name, required: true, autofocus: true %>
					    <%= f.input :end_date, :label => "Completion date", required: true, :as => :date,:start_year => 2015,:end_year => 2030,:order => [:year] %>
					    <%= f.input :public, :label => "Make this course public", as: :boolean %>
					  </div>

					  <div class="form-actions">
					    <%= f.submit :class => 'slider_btn btn_course' %>
					  </div>
					<% end %>
            </div>
    </div>
</div>

app/views/courses/edit.html.erb
<%= render 'form' %>

app/views/courses/index.html.erb
 <!--=========== BEGAIN TEAM SECTION ================-->

    <section id="team">
      <div class="container">
      
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <!-- BEGAIN ABOUT HEADING -->
            <div class="heading">
              <h2 class="wow fadeInLeftBig">My Courses</h2>            
            </div>            
            <div class="team_area">
              <!-- BEGAIN TEAM SLIDER -->
              <div class="team_slider">  
              <% @courses.each do |course| %>
                <!-- BEGAIN SINGLE TEAM SLIDE#1 -->              
                <div class="col-lg-3 col-md-3 col-sm-4">
                  <div class="single_team wow fadeInUp">
                  <%= link_to user_course_path(current_user, course) do %>
                    <div class="team_img">
                      <img src="http://thumbs.dreamstime.com/z/stack-books-doodle-vector-32031106.jpg" alt="img">
                    </div>                  
                    <% if course.public || course.user == current_user %>
                    <h5 class=""><%= course.name %></h5>                    
                  <% end %>
                <% end %>
                  </div>
                </div> 
                <% end %>                           
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--=========== END TEAM SECTION ================-->
          <div class="container">
      
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <!-- BEGAIN ABOUT HEADING -->
            
              <h2 class="wow fadeInLeftBig"><%= link_to 'Add a course', new_user_course_path(current_user), :class => 'slider_btn'  %></h2>  


</div>
</div>
</div>
     <!--=========== BEGAIN SUBSCRIBE SECTION ================-->
    <section id="subscribe">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <!-- START SUBSCRIBE HEADING -->
            <div class="heading">
              <h2 class="wow fadeInLeftBig">Search</h2>
              <p>Look for other students you many know and see what they are up to.</p>
            </div>
            <!-- BEGAIN SUBSCRIVE FORM -->
              <div class="subscrive_group wow fadeInUp">
                <%= form_tag users_search_path, method: :get do %>
                    <%= text_field_tag :q, params[:q], :class => "form-control subscribe_mail", :type => "text", :placeholder => "Search by name, email, major..." %>
                <%= submit_tag "Search" ,:class => "subscr_btn", :type => "submit", :value => "Search" %>
                <% end %>
                <hr>

              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
    <!--=========== END SUBSCRIBE SECTION ================-->

app/views/courses/new.html.erb
<%= render 'form' %>

app/views/courses/show.html.erb
    <section id="team">
      <div class="container">

      <h2 class="wow fadeInLeftBig"><%= @course.name %></h2>            

                  <div class="heading">
            </div> 




<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          To do list
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
<%= render 'tdls/index' %>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Important dates
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
<%= render 'importants/index' %>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
         Goals
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="panel-body">
<%= render 'goals/index' %>
      </div>
    </div>
  </div>
   <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
         Files
        </a>
      </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
      <div class="panel-body">
<%= render 'uploads/index' %>
      </div>
    </div>
  </div>
</div>




<% if @course.user == current_user %>
<%= link_to 'Edit', edit_user_course_path(current_user, @course), :class => 'slider_btn'  %> | 
<%= link_to 'Delete', user_course_path(current_user, @course), method: :delete, data: {confirm: 'Are you sure?'}, :class => 'slider_btn'  %> |
<%= link_to 'Back', user_courses_path(current_user), :class => 'slider_btn'  %> 

<% end %>

</div>

</section>