config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  devise_for :users

  get "/users/search" => 'users#search'

  # complete action
  patch '/courses/:course_id/tdl/:id' => 'tdls#complete', as: :complete

  resources :users, only: [] do
  	resources :courses
  end

  resources :courses, only: [] do
  	resources :tdls
  end

  resources :courses, only: [] do
    resources :importants
  end

  resources :courses, only: [] do
    resources :goals
  end

  resources :courses, only: [] do
    resources :uploads
  end
end

app/models/goal.rb
class Goal < ActiveRecord::Base
	belongs_to :course
	belongs_to :user
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def index    
    @course = Course.find(params[:course_id])
    @goals = @course.goals.all
  end

  def show
    @course = Course.find(params[:course_id])
    @goal = @course.goals.find(params[:id])
    @goals = @course.goals.all ##
  end

  def new
    @course = Course.find(params[:course_id])
    @goal = @course.goals.new
  end

  def edit
    @course = Course.find(params[:course_id])
    @goal = @course.goals.find(params[:id])
    @edit = true 
  end

  def create
    @course = Course.find(params[:course_id])
    @goal = @course.goals.create(goal_params)
    @goals = @course.goals.all
    # render 'index'
    redirect_to user_course_path(current_user, @course) ####
  end

  def update
    @course = Course.find(params[:course_id])
    @goal = @course.goals.find(params[:id])
    
    @goals = @course.goals.all

    if @goal.update(goal_params)
      # render 'index'
      redirect_to user_course_path(current_user, @course) 
    else
      render 'edit'
    end
  end

  def destroy
    @course = Course.find(params[:course_id])
    @goal = @course.goals.find(params[:id])
    @goal.destroy
    # redirect_to course_tdls_path(@course)
    redirect_to user_course_path(current_user, @course)
  end

  private
      def goal_params
        params.require(:goal).permit(:date, :details, :projected_mark, :actual_mark).merge(user_id: current_user.id)
      end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<div class="row">

        <div class="col-md-4 col-md-offset-4 pad-top">
            <hr>
            <h2 class="intro-text text-center">
                <strong>New goal</strong>
            </h2>
            <hr>
            <div class = "sign-up  text-center" >
    		<%= simple_form_for([@course, @goal]) do |f| %>

			  <div class="form-inputs" >
			    <%= f.input :date, :as => :date %>
		 	    <%= f.input :details , required: true, autofocus: true %>
			    <%= f.input :projected_mark %>
			    <%= f.input :actual_mark %>
			  </div>

			<% if @edit %>
				  <div class="form-actions">
				    <%= f.button :submit, "Update" %>
				  </div>
				 <% else %>
				   <div class="form-actions">
				    <%= f.button :submit, "Create" %>
				  </div>
			<% end %>

			<% end %>
    
            </div>
    </div>
</div>

app/views/goals/_index.html.erb
<table class = "table">
	<tr>
		<th>Date</th>
		<th>Details</th>
		<th>Projected mark</th>
		<th>Actual mark</th>
		<th>Deviation</th>
		<th colspan='2'></th>
	</tr>
<tbody>	
	<% @goals.each do |goal| %>
	<tr>
		<td><%= goal.date %></td>
		<td><%= goal.details %></td> 
		<td><%= goal.projected_mark %></td>
		<td><%= goal.actual_mark %></td>

		<% if goal.user == current_user %>
			<% if goal.actual_mark != nil %>		
				<% deviation = goal.actual_mark - goal.projected_mark %>
				<td><%= deviation %></td>
				<td><%= link_to 'Edit', edit_course_goal_path(@course, goal) %></td>
				<td><%= link_to 'Delete', course_goal_path(@course, goal),
		          method: :delete, data: { confirm: 'Are you sure?' } %></td>
			<% else %>
				<td><%= '-' %></td>

				<td><%= link_to 'Update', edit_course_goal_path(@course, goal) %></td>
				<td><%= link_to 'Delete', course_goal_path(@course, goal),
	          			method: :delete,
	          			data: { confirm: 'Are you sure?' } %></td>
        	<% end %>
		<% end %>	
	</tr>
	<% end %>


</tbody>
</table>

</br>

<% if @course.user == current_user  %>
	<%= link_to 'Add', new_course_goal_path(@course) %> 
	<i class="glyphicon glyphicon-plus"></i>
<% end %>

app/views/goals/edit.html.erb
<%= render 'form' %>

app/views/goals/new.html.erb
<%= render 'goals/form' %>

app/views/goals/show.html.erb
<h1>Goals#show</h1>
<p>Find me in app/views/goals/show.html.erb</p>

<table class = "table">
	<tr>
		<th>Date</th>
		<th>Details/th>
		<th>Projected mark</th>
		<th>Actual mark</th>
		<th>Deviation</th>
		<th colspan='2'></th>
	</tr>
<tbody>	
	<tr>
		<td><%= @goal.date %></td>
		<td><%= @goal.event %></td> 
		<td><%= @goal.projected_mark %></td>
		<td><%= @goal.actual_mark %></td>  	
		<td><%= @deviation %></td>  	
	</tr>	
</tbody>
</table>

</br>

<%= link_to 'Add an event', new_course_goal_path(@course) %> | 
<%= link_to 'Back', course_goals_path(@course) %>